//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YourRatingsSerial
    {
        public int ID_User { get; set; }
        public int ID_Serial { get; set; }
        public Nullable<int> Nota { get; set; }
    
        public virtual Seriale Seriale { get; set; }
        public virtual User User { get; set; }
    }
}
